name: CI

on:
  push:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - run: npm ci
        name: Install packages

      - run: npm run lint
        name: Lint

      - run: npm run typecheck
        name: Typescript compile

      - run: npm run build
        name: Build
